fix: add logic contextUser for opensearch 3x

diff --git a/docker-opensearch/3x/docker/Dockerfile b/docker-opensearch/3x/docker/Dockerfile
--- a/docker-opensearch/3x/docker/Dockerfile
+++ b/docker-opensearch/3x/docker/Dockerfile
@@ -8,7 +8,10 @@ COPY 3x/opensearch-filter-plugin/pom.xml .
 RUN mvn dependency:go-offline
 
 COPY 3x/opensearch-filter-plugin /build
-RUN mvn clean package
+RUN set -eux; \
+    mvn clean package -Dcheckstyle.skip=true -DskipTests=true || \
+    (echo "⚠️ Build failed, checkstyle skipped"; exit 1)
+RUN mvn -e -X clean package
 
 FROM opensearchproject/opensearch:3.2.0
 
